### ISSUE TITLE
json media

### ISSUE THREAD

**Issue by aghili371** [moov2/Moov2.OrchardCore.Gallery#1]
please give me an example for json media value, and how can i display in customize  liguid page.

it posible to get media, directly from assest media module?

**Comment by mobinzk** [comment]
Hi Ahmad, 

This Module is still under development, however if you want to contribute and send pull request, that would be appreciated.

The json that you can use at this stage is:
`{[Url: "The image URL", type: "0"]}`

**Comment by aghili371** [comment]
hi mobin,

i'm new in orchard , at this moment iam not enough good to develop some things. but i think after sme times i could be here again.

**Comment by mobinzk** [comment]
That's alright, we'll update you once we've completed the development on this module.

**Comment by aghili371** [comment]
thank you very much
